name: Deploy Vue App to FTP

on:
  push:
    branches:
      - main  # o la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Update isobit-ui to latest
        run: npm install isobit-ui@latest
        
      - name: Build app with secrets
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
          echo "VITE_BASE=${{ secrets.VITE_BASE }}" >> .env
          echo "VITE_LOGIN_PATH=${{ secrets.VITE_LOGIN_PATH }}" >> .env
          echo "VITE_REMOTE_PATH=${{ secrets.VITE_REMOTE_PATH }}" >> .env
          npm run build

      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/
          server-dir: /erp/
